name: Build docker image
description: Builds docker image and pushes it to dockerhub
inputs:
  tags:
    required: true
    default: 'mimotej/go-jamf:latest'
  username:
    required: true
  password:
    required: true
outputs:
  build-digest:
    value: ${{ steps.build.outputs.digest }}
runs:
  using: 'composite'
  steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ inputs.tags }}
