name: Build docker image
description: Builds docker image and pushes it to dockerhub
inputs:
  tags:
    required: true
    default: 'latest'
  username:
    required: true
  password:
    required: true
  token:
    required: true
runs:
  using: 'composite'
  steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mimotej/go-jamf:${{ inputs.tags }}
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Link to DockerHub image
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📦 Link to DockerHub image: "https://hub.docker.com/layers/mimotej/go-jamf/${{ inputs.tags }}/images/${{ steps.build.outputs.digest }}"
          edit-mode: replace
          token: ${{ inputs.token}}
