---
repos:
  - repo: https://github.com/golangci/golangci-lint.git
    rev: v1.61.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
