name: Prepare deployment
description: Prepares deployment of the application PR
inputs:
  tag:
    required: true
    default: 'latest'
  PAT:
    required: true
  repo:
    required: true
  file:
    required: true
    default:  values.yaml
outputs:
  pr-link:
    value: ${{ steps.setup-pr.outputs.pull-request-url }}
runs:
  using: 'composite'
  steps: 
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        path: 'manifests'
    - name: Move to workspace folder
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/manifests
    - name: Setup yq
      id: setup-yq
      uses: chrisdickinson/setup-yq@v1.0.1
      with:
        yq-version: v4.25.3
    - name: Bump image tag
      shell: bash
      run: |
        yq -i '.image.tag = "${{ inputs.tag }}"' $GITHUB_WORKSPACE/manifests/apps/go-jamf/${{ inputs.file }}
    - name: Setup PR
      id: setup-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.PAT }}
        commit-message: "chore: Update go-jamf manifests tag: ${{ inputs.tag }}"
        branch: update-manifests
        path: manifests
        delete-branch: true
        title: Update manifests - go-jamf dev
        body: |
          This PR is automatically generated. Action that created this PR can be found here: https://github.com/mimotej/jamf-go/actions.

