name: PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions:
  pull-requests: write
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'go.mod'
              - 'main.go'
              - 'main_test.go'  
      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        uses: ./.github/actions/build-docker
        id: build
        with: 
          tags: "mimotej/go-jamf:pr-${{ github.event.number }}-${{ github.sha }},mimotej/go-jamf:pr-${{ github.event.number }}-latest"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Find Comment
        if: steps.changes.outputs.src == 'true'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Link to DockerHub image
      
      - name: Create or update comment
        if: steps.changes.outputs.src == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📦 Link to DockerHub image: "https://hub.docker.com/layers/mimotej/go-jamf/pr-${{ github.event.number }}-${{ github.sha }}/images/${{ steps.build.outputs.build-digest }}"
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
